MyCenter/MyCenter/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from apps.company import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include("product.urls", namespace='products')),
    url(r'^company/', include("company.urls", namespace='company')),
    url(r'^anti_fake/', include("anti_fake.urls", namespace='anti_fake')),
    url(r'^$', include("index.urls", namespace='index')),
]

# urlpatterns += i18n_patterns(
#     url(r'^admin/', include(admin.site.urls)),
#     prefix_default_language=True,
# )

MyCenter/apps/anti_fake/urls.py
from django.conf.urls import url
from anti_fake.views import SdyproView, RealView, RealLookView, LookView

urlpatterns = [
    url(r'^sdypro/$', SdyproView.as_view(), name='sdypro'),
    url(r'^realdata/$', RealView.as_view(), name='realdata'),
    url(r'^real_look/$', RealLookView.as_view(), name='real_look'),
    url(r'^look/(?P<pro_id>\d+)/$', LookView.as_view(), name='look'),
]

MyCenter/apps/company/urls.py
from django.conf.urls import url
from company import views

urlpatterns = [
    url(r'^(?P<c_id>\d+)$', views.company_detail, name='detail'),
    url(r'^category/$', views.company_type, name='company_type'),
    url(r'^search/', views.company_search, name='company_search'),
    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^selfcheck/', views.self_check_list, name='self_check'),
]

MyCenter/apps/product/urls.py
from django.conf.urls import url
from product.views import CategoryView, cate_proView, CateSearchView, DetailView

urlpatterns = [
    url(r'^category/', CategoryView.as_view(), name='CategoryView'),
    url(r'^search/', CateSearchView.as_view(), name='CateSearchView'),
    url(r'^(?P<pro_id>\d+)/$', DetailView.as_view(), name='DetailView'),
]

MyCenter/apps/company/models.py
from django.db import models
from db.base_model import BaseModel
from django.core.exceptions import ValidationError


class Province(BaseModel):
    name = models.CharField(max_length=32, verbose_name='省名')

    class Meta:
        verbose_name = '省'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class City(BaseModel):
    class Meta:
        verbose_name = '市'
        verbose_name_plural = verbose_name

    name = models.CharField(max_length=32, verbose_name='市名')
    province = models.ForeignKey(to=Province)

    def __str__(self):
        return self.name


class CompanyType(BaseModel):
    """企业类型"""
    type = models.CharField(max_length=20,
                            verbose_name='类型名称'
                            )

    class Meta:
        verbose_name = '企业类型'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.type


class Company(BaseModel):
    """企业用户"""

    user_name = models.CharField(verbose_name='用户名',
                                 max_length=16,
                                 unique=True,
                                 )

    password = models.CharField(verbose_name='用户密码',
                                max_length=32
                                )

    """企业信息"""

    # 状态信息
    State_choices = (
        (1, '提交,待审核'),
        (2, '审核通过'),
        (3, '审核拒绝'),
    )

    c_name = models.CharField(verbose_name='企业名称',
                              max_length=16,
                              default='',
                              blank=True
                              )

    credit_code = models.CharField(verbose_name='信用代码',
                                   max_length=64,
                                   default='',
                                   blank=True
                                   )

    legal_name = models.CharField(verbose_name='法人姓名',
                                  max_length=16,
                                  default='',
                                  blank=True
                                  )

    tel = models.CharField(verbose_name='联系电话',
                           max_length=11,
                           default='',
                           blank=True
                           )

    email = models.CharField(verbose_name='邮箱',
                             max_length=32,
                             default='',
                             blank=True
                             )

    site = models.CharField(verbose_name='注册地址',
                            max_length=64,
                            default='',
                            blank=True
                            )
    business_site = models.CharField(verbose_name='工商地址',
                                     max_length=64, )

    province = models.ForeignKey(to=Province,
                                 verbose_name='省',
                                 null=True,
                                 blank=True,
                                 )
    time_limit = models.DateField(verbose_name='营业期限',
                                  null=True,
                                  blank=True)
    scope = models.CharField(verbose_name='经营范围',
                             max_length=64,
                             default='',
                             blank=True,
                             )
    city = models.ForeignKey(to=City,
                             verbose_name='市',
                             null=True,
                             blank=True,
                             )

    c_document = models.ImageField(verbose_name='企业证件',
                                   null=True,
                                   blank=True)

    c_status = models.SmallIntegerField(verbose_name='状态',
                                        choices=State_choices,
                                        default=1,
                                        blank=True
                                        )

    c_type = models.ForeignKey(to='CompanyType',
                               verbose_name='企业类型',
                               null=True,
                               blank=True,
                               )
    c_intro = models.CharField(max_length=255,
                               verbose_name='企业简介',
                               null=True,
                               blank=True,
                               )
    c_honor = models.CharField(max_length=255,
                               verbose_name='公司荣誉',
                               null=True,
                               blank=True,
                               )

    class Meta:
        verbose_name = '企业信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.c_name

    def clean(self):
        if self.city is None or self.province is None:
            return None
        elif self.city not in self.province.city_set.all():
            raise ValidationError(_('选择的城市不属于选择的省或暂不支持该城市'))


class SelfCheckTemplate(BaseModel):
    class Meta:
        verbose_name = '自查信息'
        verbose_name_plural = verbose_name

    name = models.CharField(max_length=32, verbose_name='模板名')


class SelfCheckPlan(BaseModel):
    class Meta:
        verbose_name = '自查计划'
        verbose_name_plural = verbose_name

    company = models.ForeignKey(to=Company, verbose_name='公司')
    date = models.DateField(verbose_name='时间')
    is_active = models.BooleanField(verbose_name='是否激活', default=False)
    template = models.ForeignKey(to=SelfCheckTemplate, verbose_name='自查模板')


class SelfCheckInfo(BaseModel):
    class Meta:
        verbose_name = '自查信息'
        verbose_name_plural = verbose_name

    plan = models.ForeignKey(to=SelfCheckPlan, verbose_name='检查计划')

MyCenter/apps/company/forms.py
from django.forms import ModelForm, ModelChoiceField
from company.models import Company, Province, City, CompanyType


class RegisterForm(ModelForm):
    class Meta:
        model = Company
        exclude = ['State_choices']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['province'] = ModelChoiceField(queryset=Province.objects.all(), required=False)
        self.fields['city'] = ModelChoiceField(queryset=City.objects.all(), required=False)
        self.fields['c_type'] = ModelChoiceField(queryset=CompanyType.objects.all(), required=False)

MyCenter/apps/company/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, Http404, redirect
from django.views import View
from company.models import CompanyType, Company, Province, City, SelfCheckPlan
from product.models import Category
from django.core import serializers
from company.forms import RegisterForm


def company_detail(request, c_id):
    company = get_object_or_404(Company, pk=c_id)
    company_types = CompanyType.objects.all()
    product_types = Category.objects.all()
    context = {'company': company,
               'company_types': company_types,
               'product_types': product_types}
    return render(request, 'company_detail.html', context=context)


def company_type(request):
    pass


def company_search(request):
    c_prov = request.GET.get('c_prov', None)
    c_city = request.GET.get('c_city', None)
    c_type = request.GET.get('c_type', None)
    company = Company.objects.all()
    company_types = CompanyType.objects.all()
    product_types = Category.objects.all()
    if c_type:
        company = company.filter(c_type=c_type)
    if c_city:
        company = company.filter(c_city=c_city)
    if c_prov:
        company = company.filter(c_pro=c_prov)
    company = company.filter(c_status=2)
    context = {'company': company,
               'company_types': company_types,
               'product_types': product_types}

    return render(request, 'company.html', context=context)


def register(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'register.html', {'form': form})

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('company:search')
        else:
            return render(request, 'register.html', {'form': form})


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')

    if request.method == 'POST':
        company = Company.objects.filter(user_name=request.POST.get('user_name', '')).first()
        if company and company.password == request.POST.get('password', ''):
            request.session['user'] = company.pk
            return redirect('company:search')
        else:
            return redirect('company:login')


def self_check_list(request):
    company_types = CompanyType.objects.all()
    product_types = Category.objects.all()
    company = request.GET.get('city', None)
    plans = SelfCheckPlan.objects.all()
    if company:
        plans = plans.filter(company=company)

    return render(request, 'comprePlan.html', context={'plans': plans,
                                                       'company_types': company_types,
                                                       'product_types': product_types})

MyCenter/apps/product/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.core import serializers
from django.http import JsonResponse
from product.models import Category, Product
from company.models import Company, CompanyType
import json


class DetailView(View):
    def get(self, request, pro_id=0):
        pro_id = int(pro_id)
        good_info = Product.objects.get(pk=pro_id)
        company_types = CompanyType.objects.all()
        product_types = Category.objects.all()
        # print(good_info)
        context = {
            'good_info': good_info,
            'company_types': company_types,
            'product_types': product_types
        }
        return render(request, 'details.html', context)

    def post(self, request):
        pass


# 对应分类下的商品
class CategoryView(View):
    def get(self, request):
        company_types = CompanyType.objects.all()
        product_types = Category.objects.all()
        cate_id = request.GET.get('p_type')
        if not cate_id:
            return JsonResponse({'error': 2, 'msg': '参数不存在!'})
        try:
            cate_id = int(cate_id)
        except:
            return JsonResponse({'error': 3, 'msg': '参数错误!'})
        # 根据传来的cate_id找到对应分类
        category = Category.objects.get(pk=cate_id)
        # 获取对应产品
        goods = category.product_set.all()
        # goods_data = serializers.serialize('json', goods)
        # goods_data = json.loads(goods_data)
        # list = []
        # for good in goods_data:
        #     good['error'] = 0
        #     list.append(good)
        # goods_data = json.dumps(list)
        # print(goods_data)
        # return JsonResponse({'data': goods, 'error': 0})
        # return HttpResponse(goods_data, content_type='application/json')
        return render(request, 'product.html', {'products': goods,
                                                'company_types': company_types,
                                                'product_types': product_types
                                                })

    def post(self, requtst):
        pass


# 产品分类
class cate_proView(View):
    def get(self, requesrt):
        cates = Category.objects.all()
        cates = serializers.serialize('json', cates)
        return HttpResponse(cates, content_type='application/json')

    def post(self, request):
        pass


# 搜索
class CateSearchView(View):
    def get(self, request):
        c_prov = request.GET.get('c_prov', None)
        c_city = request.GET.get('c_city', None)
        c_name = request.GET.get('c_name', None)
        p_name = request.GET.get('p_name', None)
        company_types = CompanyType.objects.all()
        product_types = Category.objects.all()
        if p_name:
            products = Product.objects.filter(p_name=p_name)
            return render(request, 'product.html', {'products': products,
                                                    'company_types': company_types,
                                                    'product_types': product_types})
        elif c_prov:
            company = Company.objects.filter(province=c_prov)
            if c_city:
                company = company.filter(city=c_city)
            if c_name:
                company = company.filter(p_name=c_name)
            products = company.product_set.all()
            return render(request, 'product.html', {'products': products,
                                                    'company_types': company_types,
                                                    'product_types': product_types})
        else:
            products = Product.objects.all()
            return render(request, 'product.html', {'products': products,
                                                    'company_types': company_types,
                                                    'product_types': product_types})

    def post(self, request):
        pass

MyCenter/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>首页</title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/layui.css' %}">
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    {% block meta_css %}{% endblock %}
    {% block meta_js %}{% endblock %}
</head>

<body style="height:100%; width:100%">
<header>
    <img class="logo_img" src="https://img.xiaopiu.com/userImages/img2664166613f66c8.png">
    全国产品防伪溯源验证公共平台大数据监管中心
</header>
<div class="menu_div">
    <ul class="layui-nav" lay-filter="">
        <li class="layui-nav-item">
            <a href="javascript:;">企业管理</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                {% for type in company_types %}
                <dd><a href="{% url 'company:company_search' %}?c_type={{type.pk}}">{{type.type}}</a></dd>
                {% endfor %}
            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">产品管理</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                {% for type in product_types %}
                <dd><a href="{% url 'products:CategoryView' %}?p_type={{type.pk}}">{{type.cate_name}}</a></dd>
                {% endfor %}

            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">防伪溯源监管</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a href="../../zfscsupervise/prosts.html">防伪产品统计</a></dd>
                <dd><a href="../../zfscsupervise/sdypro.html">假冒伪劣产品统计</a></dd>
                <dd><a href="../../zfscsupervise/reltmdtshow.html">实时数据展示</a></dd>
                <dd><a href="../../zfscsupervise/reltmdtshow-look.html">实时数据展示查看</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">执法检查</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a href="/examination/planaudit.html">检查计划</a></dd>
                <dd><a href="/examination/enforcement.html">移动执法</a></dd>
                <dd><a href="/examination/checkresult.html">检查结果</a></dd>
                <dd><a href="/examination/expirationnotice.html">证件到期提示</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">企业自查</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a href="../../etpcompre/comprePlan.html">自查计划</a></dd>
                <dd><a href="../../etpcompre/compreInfo.html">自查信息</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">社会监督</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a href="/social_supervision/eventsreport.html">事件举报(假冒伪劣)</a></dd>
                <dd><a href="/social_supervision/productreport.html">产品举报(假冒伪劣)</a></dd>
                <dd><a href="/social_supervision/complaint.html">投诉处理</a></dd>

            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">黑名单</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a href="/blacklist/blacklist.html">黑名单管理</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">风险预警</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a href="/risk/risk_1.html">风险事件分布</a></dd>
                <dd><a href="/risk/risk_2.html">假冒伪劣事件分布</a></dd>
                <dd><a href="/risk/risk_3.html">预警信息发布</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">监管业务</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a href="/supervise/self_inspection.html">自查模板</a></dd>
                <dd><a href="/supervise/regulation.html">监管模板</a></dd>
                <dd><a href="/supervise/type.html">执法类型</a></dd>
            </dl>
        </li>
        <li class="layui-nav-item">
            <a href="javascript:;">用户信息</a>
            <dl class="layui-nav-child"> <!-- 二级菜单 -->
                <dd><a href="/user/info.html">个人信息修改</a></dd>
                <dd><a href="/user/pd.html">密码修改</a></dd>
            </dl>
        </li>
    </ul>
</div>

{% block content %}

{% endblock %}

{% block footer %}

{% endblock %}


<script src="{% static 'js/layui.all.js' %}"></script>
<script src="{% static 'js/left.js' %}"></script>
<script src="{% static 'js/check.js' %}"></script>
{% block footer_js %}

{% endblock %}
</body>

</html>

MyCenter/templates/chart_test.html
{% extends 'base.html' %}


{% block meta_js %}
{% for jsfile_name in script_list %}
<script src="{{ host }}/{{ jsfile_name }}.js"></script>
{% endfor %}
{% endblock %}

{% block content %}
{{ myechart|safe }}
{% endblock %}

MyCenter/templates/company.html
{% extends 'base.html' %}
{% load static %}

{% block meta_css %}
<link rel="stylesheet" href="{% static 'css/business.css'%}">

<style>
.layui-table th {
  height: 48px;
  text-align: center;
  background: rgba(210, 207, 207, 1);
}
.layui-table td{
  text-align: center;
  overflow: hidden;
  position: relative;
}
.layui-table {
  margin: 13px 0;
}
tbody>tr:nth-child(odd) td{
  background: #f0f0f0;
}
tbody>tr:nth-child(even) td{
  background: white;
}
/*.layui-tab-title>li{*/
  /*border: none;*/
/*}*/




</style>
{% endblock %}

<body>
<header>
    <img class="logo_img" src="https://img.xiaopiu.com/userImages/img2664166613f66c8.png">
    全国产品防伪溯源验证公共平台大数据监管中心
</header>
{% block content %}
<div class="content layui-row">
    <div class="left_div layui-col-xs2">

<span class="layui-breadcrumb" lay-separator=">">
                <a href="">首页</a>
                <a href="">企业管理</a>
                <a><cite>种养殖企业</cite></a>
            </span>
        <select id="" class="new_input" style="height: 30px">
            <option value="">企业类别</option>
            <option value="">种养殖企业</option>
            <option value="">生产企业</option>
            <option value="">学校单位食堂</option>
            <option value="">流通企业</option>
            <option value="">餐饮企业</option>
            <option value="">三小企业</option>
            <option value="">其它企业</option>
        </select>

        <select id="" class="new_input" style="height: 30px">
            <option value="">选择省</option>
            <option value="">北京</option>
            <option value="">广东</option>
            <option value="">山东</option>
            <option value="">江苏</option>
            <option value="">河南</option>
            <option value="">河北</option>
            <option value="">浙江</option>
            <option value="">陕西</option>
        </select>
        <select id="" class="new_input" style="height: 30px">
            <option value="">选择市</option>
            <option value="">济南</option>
            <option value="">南京</option>
            <option value="">上海</option>
            <option value="">石家庄</option>


        </select>
        <div style="margin-top:11px">
            <button type="button" class="btn  btn-reg">确认</button>
        </div>
        <div style="margin-top: 44px; ">
            <button class="btn  btn-other">导出Excel</button>
        </div>


    </div>

    <div class="layui-col-xs10 ">
        <div>
            <table class="layui-table " lay-even lay-skin="line">
                <colgroup>
                    <col width="150">
                    <col width="200">
                    <col>
                </colgroup>
                <thead>
                <tr>
                    <th>选择</th>
                    <th>企业名称</th>
                    <th>信用代码</th>
                    <th>联系方式</th>
                    <th>注册地址</th>
                    <th>是否防伪</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for c in company %}
                <tr>
                    <td><label><input type="checkbox"><span></span></label></td>
                    <td>{{c.c_name}}</td>
                    <td>{{c.credit_code}}</td>
                    <td>{{c.tel}}</td>
                    <td>{{c.site}}</td>
                    <td class="anti-fake">是</td>
                    <td><a href="{% url 'company:detail' c.pk %}">查看</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
            <!--<div class="layui-tab layui-tab-brief" lay-filter="docDemoTabBrief">-->
            <!--<ul class="layui-tab-title">-->
            <!--<li class="layui-this">网站设置</li>-->
            <!--<li>用户管理</li>-->
            <!--<li>权限分配</li>-->
            <!--<li>商品管理</li>-->
            <!--<li>订单管理</li>-->
            <!--</ul>-->
            <!--<div class="layui-tab-content" style="height: 100px;">-->
            <!--<div class="layui-tab-item layui-show">内容不一样是要有，因为你可以监听tab事件（阅读下文档就是了）</div>-->
            <!--<div class="layui-tab-item">内容2</div>-->
            <!--<div class="layui-tab-item">内容3</div>-->
            <!--<div class="layui-tab-item">内容4</div>-->
            <!--<div class="layui-tab-item">内容5</div>-->
            <!--</div>-->
            <!--</div>-->
        </div>
    </div>
</div>
{% endblock %}

MyCenter/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>登录界面</title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/layui.css' %}">
<script src="{% static 'js/layui.all.js' %}"></script>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<style>
  @font-face {
    font-family: 'icomoon';
    src: url('static/layui/font2/icomoon.eot?u4m6fy');
    src: url('static/layui/font2/icomoon.eot?u4m6fy#iefix') format('embedded-opentype'),
      url('static/layui/font2/icomoon.ttf?u4m6fy') format('truetype'),
      url('static/layui/font2/icomoon.woff?u4m6fy') format('woff'),
      url('static/layui/font2/icomoon.svg?u4m6fy#icomoon') format('svg');
    font-weight: normal;
    font-style: normal;
  }

  [class^="icon-"],
  [class*=" icon-"] {
    /* use !important to prevent issues with browser extensions that change fonts */
    font-family: 'icomoon' !important;
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;

    /* Better Font Rendering =========== */
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }

  .icon-logg:before {
    content: "\e915";
  }

  .icon-manager:before {
    content: "\e916";
  }

  .icon-user:before {
    content: "\e917";
  }

  .icon-data:before {
    content: "\e918";
  }

  .icon-sysmanager:before {
    content: "\e919";
  }

  .icon-list:before {
    content: "\e91a";
  }

  .icon-passagewaymanager:before {
    content: "\e91b";
  }

  .icon-base:before {
    content: "\e91c";
  }

  .icon-agentlist:before {
    content: "\e91d";
  }

  .icon-configure:before {
    content: "\e91e";
  }

  .icon-flow:before {
    content: "\e91f";
  }

  .icon-orderlist:before {
    content: "\e920";
  }

  .icon-ydlist:before {
    content: "\e921";
  }

  .icon-agentpay:before {
    content: "\e922";
  }

  .icon-agentsum:before {
    content: "\e923";
  }

  .icon-passagewaysum:before {
    content: "\e924";
  }

  .icon-custom:before {
    content: "\e925";
  }

  .icon-address:before {
    content: "\e926";
  }

  .icon-lock:before {
    content: "\e927";
  }

  body {
    color: #fff;
    font-family: "微软雅黑";
    font-size: 14px;
  }

  .wrap1 {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto
  }

  .main_content {
    background: url({% static 'image/main_bg.png' %}) repeat;
    margin-left: auto;
    margin-right: auto;
    text-align: left;
    float: none;
    border-radius: 8px;
  }

  .form-group {
    position: relative;
  }

  .login_btn {
    display: block;
    background: #3872f6;
    color: #fff;
    font-size: 15px;
    width: 100%;
    line-height: 50px;
    border-radius: 3px;
    border: none;
  }

  .login_input {
    width: 100%;
    border: 1px solid #3872f6;
    border-radius: 3px;
    line-height: 40px;
    padding: 2px 5px 2px 30px;
    background: none;
  }

  .icon_font {
    position: absolute;
    bottom: 15px;
    left: 10px;
    font-size: 18px;
    color: #3872f6;
  }

  .font16 {
    font-size: 16px;
  }

  h2 {
    margin-top: 20px;
    margin-bottom: 35px;
  }

  @media (min-width:200px) {
    .pd-xs-20 {
      padding: 20px;
    }
  }

  @media (min-width:768px) {
    .pd-sm-50 {
      padding: 50px;
    }
  }

  #grad {
    background: -webkit-linear-gradient(#4990c1, #52a3d2, #6186a3);
    /* Safari 5.1 - 6.0 */
    background: -o-linear-gradient(#4990c1, #52a3d2, #6186a3);
    /* Opera 11.1 - 12.0 */
    background: -moz-linear-gradient(#4990c1, #52a3d2, #6186a3);
    /* Firefox 3.6 - 15 */
    background: linear-gradient(#4990c1, #52a3d2, #6186a3);
    /* 标准的语法 */
  }
  p{
    margin-bottom: 10px;
  }
</style>  <style>


  </style>
</head>

<body style="background:url({% static 'image/login_bg.jpg' %}) no-repeat;">
  <div class="container wrap1" style="height:450px;">
    <h2 class="mg-b20 text-center">全国产品防伪溯源验证公共平台</h2>
    <div class="col-sm-8 col-md-5 center-auto pd-sm-50 pd-xs-20 main_content">
      <p class="text-center font16">用户登录</p>
      <form action="" method="post">
        <div class="form-group mg-t20">
          <i class="icon-user icon_font"></i>
          <input name="user_name" type="text" class="login_input" id="Email1" placeholder="请输入用户名" />
        </div>
        <div class="form-group mg-t20">
          <i class="icon-lock icon_font"></i>
          <input name="password" type="password" class="login_input" id="Password1" placeholder="请输入密码" />
        </div>
        <div class="checkbox mg-b25">
          <label>
            <input type="checkbox" />记住我的登录信息
          </label>
        </div>
        <button type="button" style="submit" id="login_btn" class="login_btn">登 录</button>
          <div style="height:15px"></div>
          <a href="{% url 'company:register' %}"><button type="button" style="button" class="login_btn">注册</button></a>
      </form>

    </div>
    <!--row end-->
  </div>
  <!--container end-->
</body>
<script>

  $(function () {
    $("#login_btn").click(function () {
      if ($("#Email1").val().trim() == "" || $("#Password1").val().trim() == "") {
        alert("用户名或密码为空");
        return;
      }
      if ($("#Email1").val().trim() != "admin" || $("#Password1").val().trim() != "admin123") {
        alert("用户名密码错误");
        return;
      }


      location.href = "/home.html";
    })



      window.onkeydown = function (e) {
    var e = e || window.event;
    if (e.keyCode == 13) {
     $("#login_btn").click();
    }
  }
  })


</script>

</html>