MyCenter/MyCenter/urls.py
from django.conf.urls import url, include
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from apps.company import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^product/', include("product.urls", namespace='products')),
    url(r'^company/', include("company.urls", namespace='company')),
    url(r'^anti_fake/', include("anti_fake.urls", namespace='anti_fake')),
    url(r'^$', include("index.urls", namespace='index')),
]

# urlpatterns += i18n_patterns(
#     url(r'^admin/', include(admin.site.urls)),
#     prefix_default_language=True,
# )

MyCenter/apps/product/urls.py
from django.conf.urls import url
from product.views import CategoryView, cate_proView, CateSearchView, DetailView

urlpatterns = [
    url(r'^category/', CategoryView.as_view(), name='CategoryView'),
    url(r'^search/', CateSearchView.as_view(), name='CateSearchView'),
    url(r'^(?P<pro_id>\d+)/$', DetailView.as_view(), name='DetailView'),
]

MyCenter/apps/product/models.py
from django.db import models
from db.base_model import BaseModel
from company.models import Company


class Category(BaseModel):
    """产品分类"""
    cate_name = models.CharField(max_length=20,
                                 verbose_name="类型名称",
                                 )

    def __str__(self):
        return self.cate_name

    class Meta:
        # 定义在后台显示的名称
        verbose_name = "产品分类"
        # 定义复数时的名称(去掉s)
        verbose_name_plural = verbose_name


class Product(BaseModel):
    """产品详情"""
    is_status_choices = (
        (0, "初始化"),
        (1, "提交申请"),
        (2, "生产防伪码")
    )
    p_name = models.CharField(verbose_name="产品名称",
                              max_length=50
                              )
    p_type = models.CharField(verbose_name="产品类型",
                              max_length=20
                              )
    company = models.ForeignKey(to=Company,
                                verbose_name="生产厂商",
                                )
    p_standard = models.CharField(verbose_name="产品规格",
                                  max_length=20
                                  )
    p_date = models.DateField(verbose_name="生产日期")
    p_period = models.CharField(verbose_name="保质期",
                                max_length=20
                                )
    p_place = models.CharField(verbose_name="产地",
                               max_length=20
                               )
    p_number = models.CharField(verbose_name='产品编号',
                                max_length=15,
                                )
    anti_fake_logo = models.CharField(verbose_name="防伪标识",
                                      max_length=20,
                                      default="logo",
                                      )
    category_name = models.ForeignKey(to="Category",
                                      verbose_name="分类"
                                      )
    p_status = models.BooleanField(verbose_name="状态",
                                   choices=is_status_choices,
                                   default=0
                                   )
    p_feature = models.CharField(verbose_name="特色",
                                 # 允许表单验证为空
                                 blank=True,
                                 # 允许数据库为空
                                 null=True,
                                 max_length=250
                                 )
    p_operate = models.CharField(verbose_name="生产工艺",
                                 blank=True,
                                 null=True,
                                 max_length=250
                                 )

    def __str__(self):
        return self.p_name

    class Meta:
        # 定义在后台显示的名称
        verbose_name = "产品详情"
        # 定义复数时的名称(去掉s)
        verbose_name_plural = verbose_name

MyCenter/apps/product/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.core import serializers
from django.http import JsonResponse
from product.models import Category, Product
from company.models import Company, CompanyType
import json


class DetailView(View):
    def get(self, request, pro_id=0):
        pro_id = int(pro_id)
        good_info = Product.objects.get(pk=pro_id)
        company_types = CompanyType.objects.all()
        product_types = Category.objects.all()
        # print(good_info)
        context = {
            'good_info': good_info,
            'company_types': company_types,
            'product_types': product_types
        }
        return render(request, 'details.html', context)

    def post(self, request):
        pass


# 对应分类下的商品
class CategoryView(View):
    def get(self, request):
        company_types = CompanyType.objects.all()
        product_types = Category.objects.all()
        cate_id = request.GET.get('p_type')
        if not cate_id:
            return JsonResponse({'error': 2, 'msg': '参数不存在!'})
        try:
            cate_id = int(cate_id)
        except:
            return JsonResponse({'error': 3, 'msg': '参数错误!'})
        # 根据传来的cate_id找到对应分类
        category = Category.objects.get(pk=cate_id)
        # 获取对应产品
        goods = category.product_set.all()
        # goods_data = serializers.serialize('json', goods)
        # goods_data = json.loads(goods_data)
        # list = []
        # for good in goods_data:
        #     good['error'] = 0
        #     list.append(good)
        # goods_data = json.dumps(list)
        # print(goods_data)
        # return JsonResponse({'data': goods, 'error': 0})
        # return HttpResponse(goods_data, content_type='application/json')
        return render(request, 'product.html', {'products': goods,
                                                'company_types': company_types,
                                                'product_types': product_types
                                                })

    def post(self, requtst):
        pass


# 产品分类
class cate_proView(View):
    def get(self, requesrt):
        cates = Category.objects.all()
        cates = serializers.serialize('json', cates)
        return HttpResponse(cates, content_type='application/json')

    def post(self, request):
        pass


# 搜索
class CateSearchView(View):
    def get(self, request):
        c_prov = request.GET.get('c_prov', None)
        c_city = request.GET.get('c_city', None)
        c_name = request.GET.get('c_name', None)
        p_name = request.GET.get('p_name', None)
        company_types = CompanyType.objects.all()
        product_types = Category.objects.all()
        if p_name:
            products = Product.objects.filter(p_name=p_name)
            return render(request, 'product.html', {'products': products,
                                                    'company_types': company_types,
                                                    'product_types': product_types})
        elif c_prov:
            company = Company.objects.filter(province=c_prov)
            if c_city:
                company = company.filter(city=c_city)
            if c_name:
                company = company.filter(p_name=c_name)
            products = company.product_set.all()
            return render(request, 'product.html', {'products': products,
                                                    'company_types': company_types,
                                                    'product_types': product_types})
        else:
            products = Product.objects.all()
            return render(request, 'product.html', {'products': products,
                                                    'company_types': company_types,
                                                    'product_types': product_types})

    def post(self, request):
        pass

MyCenter/templates/product/product.html
{% extends 'public/base.html' %}
{% load static %}

{% block product %}
    {% for category in categorys %}
        <dd><a href="{% url 'products:CategoryView' category.pk %}">{{ category.cate_name }}</a></dd>
    {% endfor %}

{% endblock %}

{% block content %}
    <tr>
        <td style="height:100%; width:100%">
            <table class="left_right">
                <tr class="left_right_tr">
                    <td class="td_left">
                        <table style="height:100%; width:100%">
                            <tr>
                                <td>
                                    <div class="left_div">
  <span class="layui-breadcrumb" lay-separator=">">
    <a href="">首页</a>
    <a href="">
      产品管理</a>
    <a><cite>
        工业产品</cite></a>
  </span>
                                        <select name="" id="" class="new_select">
                                            <option value="">选择省</option>
                                            <option value="">北京</option>
                                            <option value="">上海</option>
                                            <option value="">重庆</option>
                                            <option value="">天津</option>
                                            <option value="">四川</option>
                                            <option value="">黑龙江</option>
                                            <option value="">吉林</option>
                                            <option value="">辽宁</option>
                                            <option value="">内蒙古</option>
                                            <option value="">新疆</option>
                                        </select>
                                        <select name="" id="" class="new_select">
                                            <option value="">选择市</option>
                                            <option value="">成都</option>
                                            <option value="">郑州</option>
                                            <option value="">长春</option>
                                            <option value="">呼和浩特</option>
                                            <option value="">乌鲁木齐</option>
                                            <option value="">拉萨</option>
                                            <option value="">沈阳</option>
                                            <option value="">杭州</option>
                                            <option value="">江苏</option>
                                            <option value="">南京</option>
                                        </select>
                                        <select name="" id="" class="new_select">
                                            <option value="">选择企业</option>
                                            <option value="">广州广达酒厂</option>
                                            <option value="">江西万顷农场</option>
                                            <option value="">四川飞训信息技术有限公司</option>
                                            <option value="">内蒙古毛牦牛牛肉加工厂</option>
                                            <option value="">江北皮革厂</option>
                                            <option value="">四川盾台酒厂</option>
                                            <option value="">河南多汇食品加工厂</option>
                                            <option value="">山西黑大哥煤矿开采公司</option>
                                            <option value="">江东集团</option>
                                            <option value="">北魏集团</option>
                                            <option value="">西蜀集团</option>
                                        </select>
                                        <select name="" id="" class="new_select">
                                            <option value="">选择产品</option>
                                            <option value="">广达酒</option>
                                            <option value="">万顷红富士</option>
                                            <option value="">毛毛牦牛牛肉干</option>
                                            <option value="">江北皮鞋</option>
                                            <option value="">江北皮包</option>
                                            <option value="">江北皮夹克</option>
                                            <option value="">盾台啤酒</option>
                                            <option value="">多汇火腿肠</option>
                                            <option value="">黑大哥蜂窝煤</option>
                                            <option value="">多汇冷鲜肉</option>
                                        </select>
                                        <div style="margin: 25px 5px" style="text-align: center">
                                            <button type="button" class="btn  btn-reg">确认</button>
                                        </div>
                                        <table style="margin-left: 30px">
                                            <tr>
                                                <td style="text-align: center">
                                                    <div>
                                                        <button id="check_all" class="btn  btn-other"
                                                                style="background: #999">全选
                                                        </button>
                                                    </div>
                                                </td>
                                                <td style="text-align: center">
                                                    <div style="margin: 5px 3px">
                                                        <button class="btn  btn-other">导出Excel</button>
                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:100%; width:100%; background-color: rgba(133, 185, 241, 1) "></td>
                            </tr>
                        </table>
                    </td>
                    <td class="td_right" style="width: 100%">
                        <table style="height:100%; width:100%">
                            <tr>
                                <td style="text-align:center">
                                    <div style="margin-top:-8px;margin-left: 2px">
                                        <table class="layui-table table_" lay-skin="line">
                                            <tr>
                                                <th>选择</th>
                                                <th>产品名称</th>
                                                <th>产品类型</th>
                                                <th>生产厂家</th>
                                                <th>产品规格</th>
                                                <th>生产日期</th>
                                                <th>保质期</th>
                                                <th>产地</th>
                                                <th>防伪标识</th>
                                                <th>操作</th>
                                                <th></th>
                                            </tr>
                                            {% for good in goods %}

                                                <tr class="single">
                                                    <td><label><input type="checkbox"
                                                                      name="td_checkbox"><span
                                                            name="false"></span></label>
                                                    </td>
                                                    <td>{{ good.p_name }}</td>
                                                    <td>{{ good.p_type }}</td>
                                                    <td>{{ good.company }}</td>
                                                    <td>{{ good.p_standard }}</td>
                                                    <td>{{ good.p_date.isoformat }}</td>
                                                    <td>{{ good.p_period }}</td>
                                                    <td>{{ good.p_place }}</td>
                                                    <td>logo</td>
                                                    <td><a href="{% url 'products:DetailView' good.pk %}">详情</a></td>
                                                    <td></td>
                                                </tr>

                                            {% endfor %}
                                        </table>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td style="height:100%; width:100%"></td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
{% endblock %}

{% block footer_js %}
    <script>
        $(function () {
            $("#check_all").on("change",function () {
                console.debug(this)
            });
        })
    </script>
{% endblock %}